name: Parent Action
author: Microsoft Corporation
description: This is a parent action that calls a child action

runs:
  using: composite
  steps:
    - name: Say hi
      shell: powershell
      run: |
        Write-Host "Hello from the Parent Action"
        Write-Host "Current action path: ${{ github.action_path }}"

    #Call child action from the same repository
    - name: Say hi from a child action
      uses: ${github.action_path}/ChildAction
      with:
        who: 'Parent Action'

branding:
  icon: terminal
  color: blue
