name: Parent Action
author: Microsoft Corporation
description: This is a parent action that calls a child action

runs:
  using: composite
  steps:
    - name: Say hi
      shell: powershell
      run: |
        Write-Host "Hello from the Parent Action"
        Write-Host "Current action path: ${{ github.action_path }}"
        Write-Host "Current action repository: ${{ github.action_repository }}"
        Write-Host "Current action ref: ${{ github.action_ref }}"

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ env.actionRepo }}
        ref: ${{ env.actionRef }}
        path: './_AL-Go'
        lfs: true

    #Call child action from the same repository
    - name: Say hi from a child action
      uses: ./_AL-Go/Actions/ChildAction
      with:
        who: 'Parent Action'

branding:
  icon: terminal
  color: blue
