name: Load Projects to Build
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
outputs:
  ProjectsJson:
    description: An array of AL-Go projects in compressed JSON format
    value: ${{ steps.loadprojects.outputs.ProjectsJson }}
  ProjectCount:
    description: The number of loaded projects
    value: ${{ steps.loadprojects.outputs.ProjectCount }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      id: loadprojects
      run: try { ${{ github.action_path }}/LoadProjects.ps1 } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
branding:
  icon: terminal
  color: blue
